---
- name: Setup target server
  become: false
  hosts: servers
  vars:
    remote_folder: '{{ _remote_folder }}'
    project_service: '{{ _project_service }}'
    project_stage: '{{ _project_stage }}'
    project_name:  '{{ _project_name  }}'
    image_tag: '{{ _image_tag }}'
    full_registry_url: '{{ _full_registry_url }}'

  tasks:
    - name: Copy docker compose file
      template:
        src: '../+{{ project_stage }}/docker-compose.{{ project_service }}.yml.j2'
        dest: '{{ remote_folder }}/docker-compose.{{ project_service }}.yml'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'
        force: true

    - name: Create .version file
      copy:
        content: |
          {{ project_name | upper }}_{{ project_service | upper }}_VERSION={{ image_tag }}
          {{ project_name | upper }}_{{ project_service | upper }}_REGISTRY_URL={{ full_registry_url }}
        dest: '{{ remote_folder }}/.version.{{ project_service }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'
        force: true

    - name: Generate database password
      set_fact:
        db_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

    # Create database .env.database file (only if it doesn't exist) - shared across services
    - name: Create database .env.database file
      copy:
        content: |
          # Database credentials generated on {{ ansible_date_time.iso8601 }}
          POSTGRES_USER={{ db_username }}
          POSTGRES_PASSWORD={{ db_password }}
          POSTGRES_DB={{ db_name }}

          # EF connection string
          DATABASE_URL=postgres://{{ db_username }}:{{ db_password }}@{{ db_host_name }}:5432/{{ db_name }}

          # Others
          APP_HOST=127.0.0.1
          APP_PORT=4000
          DATABASE_MAX_CONNECTIONS=5
          STATIC_DIR=../frontend/build
        dest: "{{ remote_folder }}/.env.database"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        force: false

